[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/testredirect"
  to = "/cocotafadmin.html"
  status = 200
  force = true

[[redirects]]
  from = "/masina/*"
  to = "/cocotafadmin.html?debug=:splat"
  status = 200
  force = true
