[build]
  publish = "."
  functions = "netlify/functions"

[build.processing.html]
  pretty_urls = false

[[redirects]]
  from = "/masina/:id"
  to = "/.netlify/functions/masina?id=:id"
  status = 200
  force = true
